#! /bin/sh
sxhkd &
picom &
polybar principal &
if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
	xrandr --output HDMI1 --primary --mode 1920x1080 --rotate normal --output LVDS1 --mode 1366x768 --rotate normal --left-of HDMI1
fi

bspc monitor HDMI1 -n DISPLAY0 -d 4 5 6
bspc monitor LVDS1 -n DISPLAY1 -d 1 2 3
bspc monitor HDMI1 -s LVDS1

bspc desktop -f 6
bspc config window_gap 20
bspc config borderless_monocle   false
bspc config border_width 0
bspc config gapless_monocle      true
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name arrow &
tilix &
